version: '3'

includes:
  common: ./build/Taskfile.yml
  windows: ./build/windows/Taskfile.yml



dotenv: [ '.env' ]
vars:
  APP_NAME: "Nexus"
  BIN_DIR: "bin"
  DIST_DIR: "dist"
  API_URL: '{{.API_URL | default "http://localhost:1337"}}'
  VITE_PORT: '{{.WAILS_VITE_PORT | default 9245}}'
  VERSION: '{{.VERSION | default "development"}}'
  API_KEY: '{{.API_KEY | default "development"}}'
  ENV_FILE: '.env'

tasks:
  build:
    summary: Builds the application
    cmds:
      - task: "{{OS}}:build"
        vars:
          VERSION: "{{.VERSION}}"
  go:build:
    cmds:
      - cmd: go build -buildvcs=false -ldflags="-X github.com/hex-boost/hex-nexus-app/backend/updater.Version={{.VERSION}} -X github.com/hex-boost/hex-nexus-app/backend/updater.BackendURL={{.API_URL}} -X github.com/hex-boost/hex-nexus-app/backend/updater.APIToken={{.API_KEY}}" -o bin/Nexus-debug.exe .

  package:
    summary: Packages a production build of the application
    cmds:
      - task: "{{OS}}:package"

  run:
    summary: Runs the application
    cmds:
      - task: "{{OS}}:run"

  dev:
    summary: Runs the application in development mode
    cmds:
      - wails3 dev -config ./build/config.yml -port {{.VITE_PORT}}

