version: '3'

includes:
  common: ./build/Taskfile.yml

dotenv: [ '.env' ]
vars:
  APP_NAME: "Nexus"
  BIN_DIR: "bin"
  DIST_DIR: "dist"
  API_URL: '{{.API_URL | default "http://localhost:1337"}}'
  REFRESH_API_KEY: '{{.REFRESH_API_KEY}}'
  VITE_PORT: '{{.WAILS_VITE_PORT | default 9245}}'
  VERSION: '{{.VERSION | default "dev"}}'
  ENV_FILE: '.env'

tasks:
  build:
    summary: Builds the application
    cmds:
      - task: common:build
        vars:
          PRODUCTION: '{{.PRODUCTION | default "false"}}'
          VERSION: '{{.VERSION}}'
          API_URL: '{{.API_URL}}'
          REFRESH_API_KEY: '{{.REFRESH_API_KEY}}'

  go:build:
    deps:
      - task: common:clean
      - task: common:generate:icons
    cmds:
      - go build -race -tags development -gcflags="all=-N -l" -ldflags="-X github.com/hex-boost/hex-nexus-app/backend/internal/config.Version={{.VERSION}} -X github.com/hex-boost/hex-nexus-app/backend/internal/config.LogLevel=debug -X github.com/hex-boost/hex-nexus-app/backend/internal/config.Debug=true -X github.com/hex-boost/hex-nexus-app/backend/internal/config.BackendURL={{.API_URL}} -X github.com/hex-boost/hex-nexus-app/backend/internal/config.RefreshApiKey={{.REFRESH_API_KEY}}" -o bin/Nexus.exe .
      - powershell -Command "while (1) { dlv exec bin/Nexus.exe --headless --listen :2345 --api-version 2 }"

  package:
    summary: Packages a production build of the application
    cmds:
      - task: common:package
        vars:
          PRODUCTION: "true"
          VERSION: '{{.VERSION}}'
          API_URL: '{{.API_URL}}'
          REFRESH_API_KEY: '{{.REFRESH_API_KEY}}'
    method: checksum

  run:
    summary: Runs the application
    cmds:
      - task: common:run
        vars:
          VERSION: '{{.VERSION}}'

  dev:
    summary: Runs the application in development mode
    cmds:
      - wails3 dev -config ./build/config.yml -port {{.VITE_PORT}}

  coverage:
    deps: [test]
    desc: run unit tests and create HTML coverage file
    cmds:
      - go tool cover -html=coverage.txt

  fmt:
    desc: auto-format all go files
    sources:
      - "**/*.go"
    cmds:
      - gofumpt -l -w .