export type Account = {
  id: string;
  game: 'lol' | 'valorant';
  tier: string;
  rank: string;
  region: string;
  champions: number;
  skins: number;
  price: number;
  company: 'Boost Royal' | 'EBNET' | 'Public';
  status: 'Available' | 'Rented' | 'Reserved' | 'Maintenance';
  isRentedByUser?: boolean;
  refundableAmount?: number;
  expiresAt?: string;
  soloQueueRank?: {
    tier: string;
    rank: string;
    lp: number;
  };
  flexQueueRank?: {
    tier: string;
    rank: string;
    lp: number;
  };
  valorantRank?: {
    tier: string;
    rank: string;
  };
};

// Sample data
export const ACCOUNTS: Account[] = [
  {
    id: 'A7F9P2',
    game: 'lol',
    tier: 'Diamond',
    rank: 'II',
    region: 'EUW',
    champions: 145,
    skins: 78,
    price: 3200,
    company: 'Boost Royal',
    status: 'Available',
    soloQueueRank: {
      tier: 'Diamond',
      rank: 'II',
      lp: 75,
    },
    flexQueueRank: {
      tier: 'Platinum',
      rank: 'III',
      lp: 42,
    },
  },
  {
    id: 'B5M3K8',
    game: 'lol',
    tier: 'Platinum',
    rank: 'I',
    region: 'NA',
    champions: 132,
    skins: 65,
    price: 2400,
    company: 'EBNET',
    status: 'Available',
    soloQueueRank: {
      tier: 'Platinum',
      rank: 'I',
      lp: 89,
    },
  },
  {
    id: 'C2G7T4',
    game: 'lol',
    tier: 'Master',
    rank: '',
    region: 'KR',
    champions: 158,
    skins: 112,
    price: 5000,
    company: 'Boost Royal',
    status: 'Available',
    soloQueueRank: {
      tier: 'Master',
      rank: '',
      lp: 125,
    },
  },
  {
    id: 'D9R4Z1',
    game: 'lol',
    tier: 'Gold',
    rank: 'IV',
    region: 'EUNE',
    champions: 98,
    skins: 42,
    price: 1800,
    company: 'Public',
    status: 'Rented',
    soloQueueRank: {
      tier: 'Gold',
      rank: 'IV',
      lp: 32,
    },
  },
  {
    id: 'E3X8V6',
    game: 'lol',
    tier: 'Challenger',
    rank: '',
    region: 'NA',
    champions: 162,
    skins: 130,
    price: 7500,
    company: 'Boost Royal',
    status: 'Available',
    soloQueueRank: {
      tier: 'Challenger',
      rank: '',
      lp: 756,
    },
  },
  {
    id: 'F1Y5W9',
    game: 'lol',
    tier: 'Silver',
    rank: 'II',
    region: 'BR',
    champions: 85,
    skins: 30,
    price: 1200,
    company: 'EBNET',
    status: 'Reserved',
    soloQueueRank: {
      tier: 'Silver',
      rank: 'II',
      lp: 45,
    },
  },
  {
    id: 'G6U2Q7',
    game: 'lol',
    tier: 'Diamond',
    rank: 'IV',
    region: 'LAN',
    champions: 120,
    skins: 60,
    price: 2800,
    company: 'Public',
    status: 'Available',
    soloQueueRank: {
      tier: 'Diamond',
      rank: 'IV',
      lp: 12,
    },
  },
  {
    id: 'H4S9N3',
    game: 'valorant',
    tier: 'Immortal',
    rank: '3',
    region: 'JP',
    champions: 0,
    skins: 95,
    price: 6200,
    company: 'Boost Royal',
    status: 'Available',
    valorantRank: {
      tier: 'Immortal',
      rank: '3',
    },
  },
  {
    id: 'I8P5M1',
    game: 'valorant',
    tier: 'Bronze',
    rank: '1',
    region: 'OCE',
    champions: 0,
    skins: 25,
    price: 900,
    company: 'Public',
    status: 'Reserved',
    valorantRank: {
      tier: 'Bronze',
      rank: '1',
    },
  },
  {
    id: 'J2L7K9',
    game: 'valorant',
    tier: 'Iron',
    rank: '3',
    region: 'TR',
    champions: 0,
    skins: 15,
    price: 700,
    company: 'EBNET',
    status: 'Available',
    valorantRank: {
      tier: 'Iron',
      rank: '3',
    },
  },
  {
    id: 'K5H3G1',
    game: 'valorant',
    tier: 'Platinum',
    rank: '3',
    region: 'RU',
    champions: 0,
    skins: 55,
    price: 2200,
    company: 'Public',
    status: 'Available',
    valorantRank: {
      tier: 'Platinum',
      rank: '3',
    },
  },
  {
    id: 'L9F2D7',
    game: 'valorant',
    tier: 'Radiant',
    rank: '',
    region: 'EUW',
    champions: 0,
    skins: 85,
    price: 3500,
    company: 'Boost Royal',
    status: 'Available',
    valorantRank: {
      tier: 'Radiant',
      rank: '',
    },
  },
  {
    id: 'M3R7T9',
    game: 'lol',
    tier: 'Diamond',
    rank: 'I',
    region: 'NA',
    champions: 140,
    skins: 82,
    price: 3200,
    company: 'Boost Royal',
    status: 'Available',
    isRentedByUser: true,
    refundableAmount: 1600,
    expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 12).toISOString(), // 12 hours from now
    soloQueueRank: {
      tier: 'Diamond',
      rank: 'I',
      lp: 65,
    },
  },
];

// Constants
export const REGIONS = ['NA1', 'EUW1', 'EUNE1', 'OCE1'];
export const LOL_TIERS = ['Iron', 'Bronze', 'Silver', 'Gold', 'Platinum', 'Diamond', 'Master', 'Grandmaster', 'Challenger'];
export const VALORANT_TIERS = ['Iron', 'Bronze', 'Silver', 'Gold', 'Platinum', 'Diamond', 'Ascendant', 'Immortal', 'Radiant'];
export const RANKS = ['I', 'II', 'III', 'IV'];
export const COMPANIES = ['Boost Royal', 'Nexus'];
export const STATUSES = ['Available', 'Rented', 'Reserved'];
export const GAMES = ['League of Legends', 'Valorant'];

// Sample champions and skins data
export const CHAMPIONS = [
  'Aatrox',
  'Ahri',
  'Akali',
  'Akshan',
  'Alistar',
  'Amumu',
  'Anivia',
  'Annie',
  'Aphelios',
  'Ashe',
  'Aurelion Sol',
  'Azir',
  'Bard',
  'Blitzcrank',
  'Brand',
  'Braum',
  'Caitlyn',
  'Camille',
  'Cassiopeia',
  'Cho\'Gath',
  'Corki',
  'Darius',
  'Diana',
  'Dr. Mundo',
  'Draven',
  'Ekko',
  'Elise',
  'Evelynn',
  'Ezreal',
  'Fiddlesticks',
  'Fiora',
  'Fizz',
  'Galio',
  'Gangplank',
  'Garen',
  'Gnar',
  'Gragas',
  'Graves',
  'Gwen',
  'Hecarim',
  'Heimerdinger',
  'Illaoi',
  'Irelia',
  'Ivern',
  'Janna',
  'Jarvan IV',
  'Jax',
  'Jayce',
  'Jhin',
  'Jinx',
  'Kai\'Sa',
  'Kalista',
  'Karma',
  'Karthus',
  'Kassadin',
  'Katarina',
  'Kayle',
  'Kayn',
  'Kennen',
  'Kha\'Zix',
  'Kindred',
  'Kled',
  'Kog\'Maw',
  'LeBlanc',
  'Lee Sin',
  'Leona',
  'Lillia',
  'Lissandra',
  'Lucian',
  'Lulu',
  'Lux',
  'Malphite',
  'Malzahar',
  'Maokai',
  'Master Yi',
  'Miss Fortune',
  'Mordekaiser',
  'Morgana',
  'Nami',
  'Nasus',
  'Nautilus',
  'Neeko',
  'Nidalee',
  'Nocturne',
  'Nunu & Willump',
  'Olaf',
  'Orianna',
  'Ornn',
  'Pantheon',
  'Poppy',
  'Pyke',
  'Qiyana',
  'Quinn',
  'Rakan',
  'Rammus',
  'Rek\'Sai',
  'Rell',
  'Renekton',
  'Rengar',
  'Riven',
  'Rumble',
  'Ryze',
  'Samira',
  'Sejuani',
  'Senna',
  'Seraphine',
  'Sett',
  'Shaco',
  'Shen',
  'Shyvana',
  'Singed',
  'Sion',
  'Sivir',
  'Skarner',
  'Sona',
  'Soraka',
  'Swain',
  'Sylas',
  'Syndra',
  'Tahm Kench',
  'Taliyah',
  'Talon',
  'Taric',
  'Teemo',
  'Thresh',
  'Tristana',
  'Trundle',
  'Tryndamere',
  'Twisted Fate',
  'Twitch',
  'Udyr',
  'Urgot',
  'Varus',
  'Vayne',
  'Veigar',
  'Vel\'Koz',
  'Vi',
  'Viego',
  'Viktor',
  'Vladimir',
  'Volibear',
  'Warwick',
  'Wukong',
  'Xayah',
  'Xerath',
  'Xin Zhao',
  'Yasuo',
  'Yone',
  'Yorick',
  'Yuumi',
  'Zac',
  'Zed',
  'Ziggs',
  'Zilean',
  'Zoe',
  'Zyra',
];

export const SKINS = [
  'PROJECT: Ashe',
  'Dark Cosmic Jhin',
  'Spirit Blossom Ahri',
  'K/DA ALL OUT Seraphine',
  'True Damage Ekko',
  'Star Guardian Jinx',
  'Pulsefire Ezreal',
  'Elementalist Lux',
  'DJ Sona',
  'Gun Goddess Miss Fortune',
  'Cosmic Defender Xin Zhao',
  'Blood Moon Aatrox',
  'High Noon Lucian',
  'Arcade Caitlyn',
  'Pool Party Leona',
  'Battle Academia Ezreal',
  'PROJECT: Vayne',
  'Odyssey Kayn',
  'Cosmic Reaver Kassadin',
  'Nightbringer Yasuo',
  'Divine Sword Irelia',
  'God King Darius',
  'God King Garen',
  'Mecha Kingdoms Jax',
  'Coven Morgana',
  'Infernal Akali',
  'Victorious Graves',
  'Championship Riven',
  'Hextech Annie',
  'Dawnbringer Riven',
  'Bewitching Miss Fortune',
  'Lunar Beast Fiora',
  'Battle Queen Katarina',
  'Dragonslayer Pantheon',
  'Cosmic Queen Ashe',
  'Arcana Camille',
  'Cafe Cuties Bard',
  'Crystal Rose Akshan',
  'Debonair Brand',
  'Firecracker Sejuani',
  'Porcelain Kindred',
  'Shockblade Qiyana',
  'Withered Rose Syndra',
  'Anima Squad Jinx',
  'Arcana Hecarim',
  'Ashen Knight Pyke',
  'Eclipse Kayle',
  'High Noon Mordekaiser',
  'Ocean Song Seraphine',
  'Star Guardian Kai\'Sa',
];
