
export interface Account {
  id: string
  tier: string
  rank: string
  region: string
  champions: number
  skins: number
  price: number
  company: "Boost Royal" | "EBNET" | "Public"
  status: "Verified" | "Restricted"
}

// Sample data
export const ACCOUNTS: Account[] = [
  {
    id: "A7F9P2",
    tier: "Diamond",
    rank: "II",
    region: "EUW",
    champions: 145,
    skins: 78,
    price: 3200,
    company: "Boost Royal",
    status: "Verified",
  },
  {
    id: "B5M3K8",
    tier: "Platinum",
    rank: "I",
    region: "NA",
    champions: 132,
    skins: 65,
    price: 2400,
    company: "EBNET",
    status: "Verified",
  },
  {
    id: "C2G7T4",
    tier: "Master",
    rank: "",
    region: "KR",
    champions: 158,
    skins: 112,
    price: 5000,
    company: "Boost Royal",
    status: "Verified",
  },
  {
    id: "D9R4Z1",
    tier: "Gold",
    rank: "IV",
    region: "EUNE",
    champions: 98,
    skins: 42,
    price: 1800,
    company: "Public",
    status: "Restricted",
  },
  {
    id: "E3X8V6",
    tier: "Challenger",
    rank: "",
    region: "NA",
    champions: 162,
    skins: 130,
    price: 7500,
    company: "Boost Royal",
    status: "Verified",
  },
  {
    id: "F1Y5W9",
    tier: "Silver",
    rank: "II",
    region: "BR",
    champions: 85,
    skins: 30,
    price: 1200,
    company: "EBNET",
    status: "Restricted",
  },
  {
    id: "G6U2Q7",
    tier: "Diamond",
    rank: "IV",
    region: "LAN",
    champions: 120,
    skins: 60,
    price: 2800,
    company: "Public",
    status: "Verified",
  },
  {
    id: "H4S9N3",
    tier: "Grandmaster",
    rank: "",
    region: "JP",
    champions: 155,
    skins: 95,
    price: 6200,
    company: "Boost Royal",
    status: "Verified",
  },
  {
    id: "I8P5M1",
    tier: "Bronze",
    rank: "I",
    region: "OCE",
    champions: 70,
    skins: 25,
    price: 900,
    company: "Public",
    status: "Restricted",
  },
  {
    id: "J2L7K9",
    tier: "Iron",
    rank: "III",
    region: "TR",
    champions: 60,
    skins: 15,
    price: 700,
    company: "EBNET",
    status: "Verified",
  },
  {
    id: "K5H3G1",
    tier: "Platinum",
    rank: "III",
    region: "RU",
    champions: 110,
    skins: 55,
    price: 2200,
    company: "Public",
    status: "Verified",
  },
  {
    id: "L9F2D7",
    tier: "Diamond",
    rank: "I",
    region: "EUW",
    champions: 140,
    skins: 85,
    price: 3500,
    company: "Boost Royal",
    status: "Verified",
  },
]

// Constants
export const REGIONS = ["NA", "EUW", "EUNE", "KR", "BR", "LAN", "LAS", "OCE", "TR", "RU", "JP"]
export const TIERS = ["Iron", "Bronze", "Silver", "Gold", "Platinum", "Diamond", "Master", "Grandmaster", "Challenger"]
export const RANKS = ["I", "II", "III", "IV"]
export const COMPANIES = ["Boost Royal", "EBNET", "Public"]
export const STATUSES = ["Verified", "Restricted"]

// Sample champions and skins data
export const CHAMPIONS = [
  "Aatrox",
  "Ahri",
  "Akali",
  "Akshan",
  "Alistar",
  "Amumu",
  "Anivia",
  "Annie",
  "Aphelios",
  "Ashe",
  "Aurelion Sol",
  "Azir",
  "Bard",
  "Blitzcrank",
  "Brand",
  "Braum",
  "Caitlyn",
  "Camille",
  "Cassiopeia",
  "Cho'Gath",
  "Corki",
  "Darius",
  "Diana",
  "Dr. Mundo",
  "Draven",
  "Ekko",
  "Elise",
  "Evelynn",
  "Ezreal",
  "Fiddlesticks",
  "Fiora",
  "Fizz",
  "Galio",
  "Gangplank",
  "Garen",
  "Gnar",
  "Gragas",
  "Graves",
  "Gwen",
  "Hecarim",
  "Heimerdinger",
  "Illaoi",
  "Irelia",
  "Ivern",
  "Janna",
  "Jarvan IV",
  "Jax",
  "Jayce",
  "Jhin",
  "Jinx",
  "Kai'Sa",
  "Kalista",
  "Karma",
  "Karthus",
  "Kassadin",
  "Katarina",
  "Kayle",
  "Kayn",
  "Kennen",
  "Kha'Zix",
  "Kindred",
  "Kled",
  "Kog'Maw",
  "LeBlanc",
  "Lee Sin",
  "Leona",
  "Lillia",
  "Lissandra",
  "Lucian",
  "Lulu",
  "Lux",
  "Malphite",
  "Malzahar",
  "Maokai",
  "Master Yi",
  "Miss Fortune",
  "Mordekaiser",
  "Morgana",
  "Nami",
  "Nasus",
  "Nautilus",
  "Neeko",
  "Nidalee",
  "Nocturne",
  "Nunu & Willump",
  "Olaf",
  "Orianna",
  "Ornn",
  "Pantheon",
  "Poppy",
  "Pyke",
  "Qiyana",
  "Quinn",
  "Rakan",
  "Rammus",
  "Rek'Sai",
  "Rell",
  "Renekton",
  "Rengar",
  "Riven",
  "Rumble",
  "Ryze",
  "Samira",
  "Sejuani",
  "Senna",
  "Seraphine",
  "Sett",
  "Shaco",
  "Shen",
  "Shyvana",
  "Singed",
  "Sion",
  "Sivir",
  "Skarner",
  "Sona",
  "Soraka",
  "Swain",
  "Sylas",
  "Syndra",
  "Tahm Kench",
  "Taliyah",
  "Talon",
  "Taric",
  "Teemo",
  "Thresh",
  "Tristana",
  "Trundle",
  "Tryndamere",
  "Twisted Fate",
  "Twitch",
  "Udyr",
  "Urgot",
  "Varus",
  "Vayne",
  "Veigar",
  "Vel'Koz",
  "Vi",
  "Viego",
  "Viktor",
  "Vladimir",
  "Volibear",
  "Warwick",
  "Wukong",
  "Xayah",
  "Xerath",
  "Xin Zhao",
  "Yasuo",
  "Yone",
  "Yorick",
  "Yuumi",
  "Zac",
  "Zed",
  "Ziggs",
  "Zilean",
  "Zoe",
  "Zyra",
]

export const SKINS = [
  "PROJECT: Ashe",
  "Dark Cosmic Jhin",
  "Spirit Blossom Ahri",
  "K/DA ALL OUT Seraphine",
  "True Damage Ekko",
  "Star Guardian Jinx",
  "Pulsefire Ezreal",
  "Elementalist Lux",
  "DJ Sona",
  "Gun Goddess Miss Fortune",
  "Cosmic Defender Xin Zhao",
  "Blood Moon Aatrox",
  "High Noon Lucian",
  "Arcade Caitlyn",
  "Pool Party Leona",
  "Battle Academia Ezreal",
  "PROJECT: Vayne",
  "Odyssey Kayn",
  "Cosmic Reaver Kassadin",
  "Nightbringer Yasuo",
  "Divine Sword Irelia",
  "God King Darius",
  "God King Garen",
  "Mecha Kingdoms Jax",
  "Coven Morgana",
  "Infernal Akali",
  "Victorious Graves",
  "Championship Riven",
  "Hextech Annie",
  "Dawnbringer Riven",
  "Bewitching Miss Fortune",
  "Lunar Beast Fiora",
  "Battle Queen Katarina",
  "Dragonslayer Pantheon",
  "Cosmic Queen Ashe",
  "Arcana Camille",
  "Cafe Cuties Bard",
  "Crystal Rose Akshan",
  "Debonair Brand",
  "Firecracker Sejuani",
  "Porcelain Kindred",
  "Shockblade Qiyana",
  "Withered Rose Syndra",
  "Anima Squad Jinx",
  "Arcana Hecarim",
  "Ashen Knight Pyke",
  "Eclipse Kayle",
  "High Noon Mordekaiser",
  "Ocean Song Seraphine",
  "Star Guardian Kai'Sa",
]
