// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {app} from '../models';

export function Ctx():Promise<context.Context>;

export function GetHWID():Promise<string>;

export function HandleDiscordCallback(arg1:any):Promise<void>;

export function Log():Promise<app.log>;

export function SetCtx(arg1:context.Context):Promise<app.app>;

export function StartDiscordOAuth():Promise<Record<string, any>>;
