// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Ctx() {
  return window['go']['app']['app']['Ctx']();
}

export function Log() {
  return window['go']['app']['app']['Log']();
}

export function SetCtx(arg1) {
  return window['go']['app']['app']['SetCtx'](arg1);
}
