/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as ProtectedIndexImport } from './routes/_protected/index'
import { Route as ProtectedAccountsIndexImport } from './routes/_protected/accounts/index'
import { Route as ProtectedSubscriptionSubscriptionImport } from './routes/_protected/subscription/subscription'
import { Route as ProtectedAccountsIdImport } from './routes/_protected/accounts/$id'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const ProtectedIndexRoute = ProtectedIndexImport.update({
  id: '/_protected/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProtectedAccountsIndexRoute = ProtectedAccountsIndexImport.update({
  id: '/_protected/accounts/',
  path: '/accounts/',
  getParentRoute: () => rootRoute,
} as any)

const ProtectedSubscriptionSubscriptionRoute =
  ProtectedSubscriptionSubscriptionImport.update({
    id: '/_protected/subscription/subscription',
    path: '/subscription/subscription',
    getParentRoute: () => rootRoute,
  } as any)

const ProtectedAccountsIdRoute = ProtectedAccountsIdImport.update({
  id: '/_protected/accounts/$id',
  path: '/accounts/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexImport
      parentRoute: typeof rootRoute
    }
    '/_protected/accounts/$id': {
      id: '/_protected/accounts/$id'
      path: '/accounts/$id'
      fullPath: '/accounts/$id'
      preLoaderRoute: typeof ProtectedAccountsIdImport
      parentRoute: typeof rootRoute
    }
    '/_protected/subscription/subscription': {
      id: '/_protected/subscription/subscription'
      path: '/subscription/subscription'
      fullPath: '/subscription/subscription'
      preLoaderRoute: typeof ProtectedSubscriptionSubscriptionImport
      parentRoute: typeof rootRoute
    }
    '/_protected/accounts/': {
      id: '/_protected/accounts/'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof ProtectedAccountsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/': typeof ProtectedIndexRoute
  '/accounts/$id': typeof ProtectedAccountsIdRoute
  '/subscription/subscription': typeof ProtectedSubscriptionSubscriptionRoute
  '/accounts': typeof ProtectedAccountsIndexRoute
}

export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof ProtectedIndexRoute
  '/accounts/$id': typeof ProtectedAccountsIdRoute
  '/subscription/subscription': typeof ProtectedSubscriptionSubscriptionRoute
  '/accounts': typeof ProtectedAccountsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/login': typeof LoginRoute
  '/_protected/': typeof ProtectedIndexRoute
  '/_protected/accounts/$id': typeof ProtectedAccountsIdRoute
  '/_protected/subscription/subscription': typeof ProtectedSubscriptionSubscriptionRoute
  '/_protected/accounts/': typeof ProtectedAccountsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/'
    | '/accounts/$id'
    | '/subscription/subscription'
    | '/accounts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/accounts/$id'
    | '/subscription/subscription'
    | '/accounts'
  id:
    | '__root__'
    | '/login'
    | '/_protected/'
    | '/_protected/accounts/$id'
    | '/_protected/subscription/subscription'
    | '/_protected/accounts/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  LoginRoute: typeof LoginRoute
  ProtectedIndexRoute: typeof ProtectedIndexRoute
  ProtectedAccountsIdRoute: typeof ProtectedAccountsIdRoute
  ProtectedSubscriptionSubscriptionRoute: typeof ProtectedSubscriptionSubscriptionRoute
  ProtectedAccountsIndexRoute: typeof ProtectedAccountsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  LoginRoute: LoginRoute,
  ProtectedIndexRoute: ProtectedIndexRoute,
  ProtectedAccountsIdRoute: ProtectedAccountsIdRoute,
  ProtectedSubscriptionSubscriptionRoute:
    ProtectedSubscriptionSubscriptionRoute,
  ProtectedAccountsIndexRoute: ProtectedAccountsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/login",
        "/_protected/",
        "/_protected/accounts/$id",
        "/_protected/subscription/subscription",
        "/_protected/accounts/"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_protected/": {
      "filePath": "_protected/index.tsx"
    },
    "/_protected/accounts/$id": {
      "filePath": "_protected/accounts/$id.tsx"
    },
    "/_protected/subscription/subscription": {
      "filePath": "_protected/subscription/subscription.tsx"
    },
    "/_protected/accounts/": {
      "filePath": "_protected/accounts/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
