/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as ProtectedImport } from './routes/_protected'
import { Route as IndexImport } from './routes/index'
import { Route as ProtectedSubscriptionIndexImport } from './routes/_protected/subscription/index'
import { Route as ProtectedDashboardIndexImport } from './routes/_protected/dashboard/index'
import { Route as ProtectedAccountsIndexImport } from './routes/_protected/accounts/index'
import { Route as ProtectedAccountsIdImport } from './routes/_protected/accounts/$id'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const ProtectedRoute = ProtectedImport.update({
  id: '/_protected',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProtectedSubscriptionIndexRoute = ProtectedSubscriptionIndexImport.update(
  {
    id: '/subscription/',
    path: '/subscription/',
    getParentRoute: () => ProtectedRoute,
  } as any,
)

const ProtectedDashboardIndexRoute = ProtectedDashboardIndexImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => ProtectedRoute,
} as any)

const ProtectedAccountsIndexRoute = ProtectedAccountsIndexImport.update({
  id: '/accounts/',
  path: '/accounts/',
  getParentRoute: () => ProtectedRoute,
} as any)

const ProtectedAccountsIdRoute = ProtectedAccountsIdImport.update({
  id: '/accounts/$id',
  path: '/accounts/$id',
  getParentRoute: () => ProtectedRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_protected/accounts/$id': {
      id: '/_protected/accounts/$id'
      path: '/accounts/$id'
      fullPath: '/accounts/$id'
      preLoaderRoute: typeof ProtectedAccountsIdImport
      parentRoute: typeof ProtectedImport
    }
    '/_protected/accounts/': {
      id: '/_protected/accounts/'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof ProtectedAccountsIndexImport
      parentRoute: typeof ProtectedImport
    }
    '/_protected/dashboard/': {
      id: '/_protected/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardIndexImport
      parentRoute: typeof ProtectedImport
    }
    '/_protected/subscription/': {
      id: '/_protected/subscription/'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof ProtectedSubscriptionIndexImport
      parentRoute: typeof ProtectedImport
    }
  }
}

// Create and export the route tree

interface ProtectedRouteChildren {
  ProtectedAccountsIdRoute: typeof ProtectedAccountsIdRoute
  ProtectedAccountsIndexRoute: typeof ProtectedAccountsIndexRoute
  ProtectedDashboardIndexRoute: typeof ProtectedDashboardIndexRoute
  ProtectedSubscriptionIndexRoute: typeof ProtectedSubscriptionIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAccountsIdRoute: ProtectedAccountsIdRoute,
  ProtectedAccountsIndexRoute: ProtectedAccountsIndexRoute,
  ProtectedDashboardIndexRoute: ProtectedDashboardIndexRoute,
  ProtectedSubscriptionIndexRoute: ProtectedSubscriptionIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof ProtectedRouteWithChildren
  '/login': typeof LoginRoute
  '/accounts/$id': typeof ProtectedAccountsIdRoute
  '/accounts': typeof ProtectedAccountsIndexRoute
  '/dashboard': typeof ProtectedDashboardIndexRoute
  '/subscription': typeof ProtectedSubscriptionIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof ProtectedRouteWithChildren
  '/login': typeof LoginRoute
  '/accounts/$id': typeof ProtectedAccountsIdRoute
  '/accounts': typeof ProtectedAccountsIndexRoute
  '/dashboard': typeof ProtectedDashboardIndexRoute
  '/subscription': typeof ProtectedSubscriptionIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/login': typeof LoginRoute
  '/_protected/accounts/$id': typeof ProtectedAccountsIdRoute
  '/_protected/accounts/': typeof ProtectedAccountsIndexRoute
  '/_protected/dashboard/': typeof ProtectedDashboardIndexRoute
  '/_protected/subscription/': typeof ProtectedSubscriptionIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/login'
    | '/accounts/$id'
    | '/accounts'
    | '/dashboard'
    | '/subscription'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/login'
    | '/accounts/$id'
    | '/accounts'
    | '/dashboard'
    | '/subscription'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/login'
    | '/_protected/accounts/$id'
    | '/_protected/accounts/'
    | '/_protected/dashboard/'
    | '/_protected/subscription/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  LoginRoute: LoginRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_protected",
        "/login"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_protected": {
      "filePath": "_protected.tsx",
      "children": [
        "/_protected/accounts/$id",
        "/_protected/accounts/",
        "/_protected/dashboard/",
        "/_protected/subscription/"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_protected/accounts/$id": {
      "filePath": "_protected/accounts/$id.tsx",
      "parent": "/_protected"
    },
    "/_protected/accounts/": {
      "filePath": "_protected/accounts/index.tsx",
      "parent": "/_protected"
    },
    "/_protected/dashboard/": {
      "filePath": "_protected/dashboard/index.tsx",
      "parent": "/_protected"
    },
    "/_protected/subscription/": {
      "filePath": "_protected/subscription/index.tsx",
      "parent": "/_protected"
    }
  }
}
ROUTE_MANIFEST_END */
