/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as ProtectedIndexImport } from './routes/_protected/index'
import { Route as ProtectedSubscriptionImport } from './routes/_protected/subscription'
import { Route as ProtectedAccountsImport } from './routes/_protected/accounts'
import { Route as ProtectedActiveAccountsImport } from './routes/_protected/ActiveAccounts'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const ProtectedIndexRoute = ProtectedIndexImport.update({
  id: '/_protected/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProtectedSubscriptionRoute = ProtectedSubscriptionImport.update({
  id: '/_protected/subscription',
  path: '/subscription',
  getParentRoute: () => rootRoute,
} as any)

const ProtectedAccountsRoute = ProtectedAccountsImport.update({
  id: '/_protected/accounts',
  path: '/accounts',
  getParentRoute: () => rootRoute,
} as any)

const ProtectedActiveAccountsRoute = ProtectedActiveAccountsImport.update({
  id: '/_protected/ActiveAccounts',
  path: '/ActiveAccounts',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_protected/ActiveAccounts': {
      id: '/_protected/ActiveAccounts'
      path: '/ActiveAccounts'
      fullPath: '/ActiveAccounts'
      preLoaderRoute: typeof ProtectedActiveAccountsImport
      parentRoute: typeof rootRoute
    }
    '/_protected/accounts': {
      id: '/_protected/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof ProtectedAccountsImport
      parentRoute: typeof rootRoute
    }
    '/_protected/subscription': {
      id: '/_protected/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof ProtectedSubscriptionImport
      parentRoute: typeof rootRoute
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/ActiveAccounts': typeof ProtectedActiveAccountsRoute
  '/accounts': typeof ProtectedAccountsRoute
  '/subscription': typeof ProtectedSubscriptionRoute
  '/': typeof ProtectedIndexRoute
}

export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/ActiveAccounts': typeof ProtectedActiveAccountsRoute
  '/accounts': typeof ProtectedAccountsRoute
  '/subscription': typeof ProtectedSubscriptionRoute
  '/': typeof ProtectedIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/login': typeof LoginRoute
  '/_protected/ActiveAccounts': typeof ProtectedActiveAccountsRoute
  '/_protected/accounts': typeof ProtectedAccountsRoute
  '/_protected/subscription': typeof ProtectedSubscriptionRoute
  '/_protected/': typeof ProtectedIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/login' | '/ActiveAccounts' | '/accounts' | '/subscription' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/ActiveAccounts' | '/accounts' | '/subscription' | '/'
  id:
    | '__root__'
    | '/login'
    | '/_protected/ActiveAccounts'
    | '/_protected/accounts'
    | '/_protected/subscription'
    | '/_protected/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  LoginRoute: typeof LoginRoute
  ProtectedActiveAccountsRoute: typeof ProtectedActiveAccountsRoute
  ProtectedAccountsRoute: typeof ProtectedAccountsRoute
  ProtectedSubscriptionRoute: typeof ProtectedSubscriptionRoute
  ProtectedIndexRoute: typeof ProtectedIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  LoginRoute: LoginRoute,
  ProtectedActiveAccountsRoute: ProtectedActiveAccountsRoute,
  ProtectedAccountsRoute: ProtectedAccountsRoute,
  ProtectedSubscriptionRoute: ProtectedSubscriptionRoute,
  ProtectedIndexRoute: ProtectedIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/login",
        "/_protected/ActiveAccounts",
        "/_protected/accounts",
        "/_protected/subscription",
        "/_protected/"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_protected/ActiveAccounts": {
      "filePath": "_protected/ActiveAccounts.tsx"
    },
    "/_protected/accounts": {
      "filePath": "_protected/accounts.tsx"
    },
    "/_protected/subscription": {
      "filePath": "_protected/subscription.tsx"
    },
    "/_protected/": {
      "filePath": "_protected/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
