/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as OverlayImport } from './routes/overlay'
import { Route as LoginImport } from './routes/login'
import { Route as ProtectedImport } from './routes/_protected'
import { Route as IndexImport } from './routes/index'
import { Route as ProtectedToolsIndexImport } from './routes/_protected/tools/index'
import { Route as ProtectedSubscriptionIndexImport } from './routes/_protected/subscription/index'
import { Route as ProtectedPaymentsIndexImport } from './routes/_protected/payments/index'
import { Route as ProtectedNotificationsIndexImport } from './routes/_protected/notifications/index'
import { Route as ProtectedDashboardIndexImport } from './routes/_protected/dashboard/index'
import { Route as ProtectedActiveGameIndexImport } from './routes/_protected/active-game/index'
import { Route as ProtectedAccountsIndexImport } from './routes/_protected/accounts/index'
import { Route as ProtectedPaymentsIdImport } from './routes/_protected/payments/$id'
import { Route as ProtectedAccountsIdImport } from './routes/_protected/accounts/$id'

// Create/Update Routes

const OverlayRoute = OverlayImport.update({
  id: '/overlay',
  path: '/overlay',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const ProtectedRoute = ProtectedImport.update({
  id: '/_protected',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProtectedToolsIndexRoute = ProtectedToolsIndexImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => ProtectedRoute,
} as any)

const ProtectedSubscriptionIndexRoute = ProtectedSubscriptionIndexImport.update(
  {
    id: '/subscription/',
    path: '/subscription/',
    getParentRoute: () => ProtectedRoute,
  } as any,
)

const ProtectedPaymentsIndexRoute = ProtectedPaymentsIndexImport.update({
  id: '/payments/',
  path: '/payments/',
  getParentRoute: () => ProtectedRoute,
} as any)

const ProtectedNotificationsIndexRoute =
  ProtectedNotificationsIndexImport.update({
    id: '/notifications/',
    path: '/notifications/',
    getParentRoute: () => ProtectedRoute,
  } as any)

const ProtectedDashboardIndexRoute = ProtectedDashboardIndexImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => ProtectedRoute,
} as any)

const ProtectedActiveGameIndexRoute = ProtectedActiveGameIndexImport.update({
  id: '/active-game/',
  path: '/active-game/',
  getParentRoute: () => ProtectedRoute,
} as any)

const ProtectedAccountsIndexRoute = ProtectedAccountsIndexImport.update({
  id: '/accounts/',
  path: '/accounts/',
  getParentRoute: () => ProtectedRoute,
} as any)

const ProtectedPaymentsIdRoute = ProtectedPaymentsIdImport.update({
  id: '/payments/$id',
  path: '/payments/$id',
  getParentRoute: () => ProtectedRoute,
} as any)

const ProtectedAccountsIdRoute = ProtectedAccountsIdImport.update({
  id: '/accounts/$id',
  path: '/accounts/$id',
  getParentRoute: () => ProtectedRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/overlay': {
      id: '/overlay'
      path: '/overlay'
      fullPath: '/overlay'
      preLoaderRoute: typeof OverlayImport
      parentRoute: typeof rootRoute
    }
    '/_protected/accounts/$id': {
      id: '/_protected/accounts/$id'
      path: '/accounts/$id'
      fullPath: '/accounts/$id'
      preLoaderRoute: typeof ProtectedAccountsIdImport
      parentRoute: typeof ProtectedImport
    }
    '/_protected/payments/$id': {
      id: '/_protected/payments/$id'
      path: '/payments/$id'
      fullPath: '/payments/$id'
      preLoaderRoute: typeof ProtectedPaymentsIdImport
      parentRoute: typeof ProtectedImport
    }
    '/_protected/accounts/': {
      id: '/_protected/accounts/'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof ProtectedAccountsIndexImport
      parentRoute: typeof ProtectedImport
    }
    '/_protected/active-game/': {
      id: '/_protected/active-game/'
      path: '/active-game'
      fullPath: '/active-game'
      preLoaderRoute: typeof ProtectedActiveGameIndexImport
      parentRoute: typeof ProtectedImport
    }
    '/_protected/dashboard/': {
      id: '/_protected/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardIndexImport
      parentRoute: typeof ProtectedImport
    }
    '/_protected/notifications/': {
      id: '/_protected/notifications/'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof ProtectedNotificationsIndexImport
      parentRoute: typeof ProtectedImport
    }
    '/_protected/payments/': {
      id: '/_protected/payments/'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof ProtectedPaymentsIndexImport
      parentRoute: typeof ProtectedImport
    }
    '/_protected/subscription/': {
      id: '/_protected/subscription/'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof ProtectedSubscriptionIndexImport
      parentRoute: typeof ProtectedImport
    }
    '/_protected/tools/': {
      id: '/_protected/tools/'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ProtectedToolsIndexImport
      parentRoute: typeof ProtectedImport
    }
  }
}

// Create and export the route tree

interface ProtectedRouteChildren {
  ProtectedAccountsIdRoute: typeof ProtectedAccountsIdRoute
  ProtectedPaymentsIdRoute: typeof ProtectedPaymentsIdRoute
  ProtectedAccountsIndexRoute: typeof ProtectedAccountsIndexRoute
  ProtectedActiveGameIndexRoute: typeof ProtectedActiveGameIndexRoute
  ProtectedDashboardIndexRoute: typeof ProtectedDashboardIndexRoute
  ProtectedNotificationsIndexRoute: typeof ProtectedNotificationsIndexRoute
  ProtectedPaymentsIndexRoute: typeof ProtectedPaymentsIndexRoute
  ProtectedSubscriptionIndexRoute: typeof ProtectedSubscriptionIndexRoute
  ProtectedToolsIndexRoute: typeof ProtectedToolsIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAccountsIdRoute: ProtectedAccountsIdRoute,
  ProtectedPaymentsIdRoute: ProtectedPaymentsIdRoute,
  ProtectedAccountsIndexRoute: ProtectedAccountsIndexRoute,
  ProtectedActiveGameIndexRoute: ProtectedActiveGameIndexRoute,
  ProtectedDashboardIndexRoute: ProtectedDashboardIndexRoute,
  ProtectedNotificationsIndexRoute: ProtectedNotificationsIndexRoute,
  ProtectedPaymentsIndexRoute: ProtectedPaymentsIndexRoute,
  ProtectedSubscriptionIndexRoute: ProtectedSubscriptionIndexRoute,
  ProtectedToolsIndexRoute: ProtectedToolsIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof ProtectedRouteWithChildren
  '/login': typeof LoginRoute
  '/overlay': typeof OverlayRoute
  '/accounts/$id': typeof ProtectedAccountsIdRoute
  '/payments/$id': typeof ProtectedPaymentsIdRoute
  '/accounts': typeof ProtectedAccountsIndexRoute
  '/active-game': typeof ProtectedActiveGameIndexRoute
  '/dashboard': typeof ProtectedDashboardIndexRoute
  '/notifications': typeof ProtectedNotificationsIndexRoute
  '/payments': typeof ProtectedPaymentsIndexRoute
  '/subscription': typeof ProtectedSubscriptionIndexRoute
  '/tools': typeof ProtectedToolsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof ProtectedRouteWithChildren
  '/login': typeof LoginRoute
  '/overlay': typeof OverlayRoute
  '/accounts/$id': typeof ProtectedAccountsIdRoute
  '/payments/$id': typeof ProtectedPaymentsIdRoute
  '/accounts': typeof ProtectedAccountsIndexRoute
  '/active-game': typeof ProtectedActiveGameIndexRoute
  '/dashboard': typeof ProtectedDashboardIndexRoute
  '/notifications': typeof ProtectedNotificationsIndexRoute
  '/payments': typeof ProtectedPaymentsIndexRoute
  '/subscription': typeof ProtectedSubscriptionIndexRoute
  '/tools': typeof ProtectedToolsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/login': typeof LoginRoute
  '/overlay': typeof OverlayRoute
  '/_protected/accounts/$id': typeof ProtectedAccountsIdRoute
  '/_protected/payments/$id': typeof ProtectedPaymentsIdRoute
  '/_protected/accounts/': typeof ProtectedAccountsIndexRoute
  '/_protected/active-game/': typeof ProtectedActiveGameIndexRoute
  '/_protected/dashboard/': typeof ProtectedDashboardIndexRoute
  '/_protected/notifications/': typeof ProtectedNotificationsIndexRoute
  '/_protected/payments/': typeof ProtectedPaymentsIndexRoute
  '/_protected/subscription/': typeof ProtectedSubscriptionIndexRoute
  '/_protected/tools/': typeof ProtectedToolsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/login'
    | '/overlay'
    | '/accounts/$id'
    | '/payments/$id'
    | '/accounts'
    | '/active-game'
    | '/dashboard'
    | '/notifications'
    | '/payments'
    | '/subscription'
    | '/tools'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/login'
    | '/overlay'
    | '/accounts/$id'
    | '/payments/$id'
    | '/accounts'
    | '/active-game'
    | '/dashboard'
    | '/notifications'
    | '/payments'
    | '/subscription'
    | '/tools'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/login'
    | '/overlay'
    | '/_protected/accounts/$id'
    | '/_protected/payments/$id'
    | '/_protected/accounts/'
    | '/_protected/active-game/'
    | '/_protected/dashboard/'
    | '/_protected/notifications/'
    | '/_protected/payments/'
    | '/_protected/subscription/'
    | '/_protected/tools/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  LoginRoute: typeof LoginRoute
  OverlayRoute: typeof OverlayRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  LoginRoute: LoginRoute,
  OverlayRoute: OverlayRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_protected",
        "/login",
        "/overlay"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_protected": {
      "filePath": "_protected.tsx",
      "children": [
        "/_protected/accounts/$id",
        "/_protected/payments/$id",
        "/_protected/accounts/",
        "/_protected/active-game/",
        "/_protected/dashboard/",
        "/_protected/notifications/",
        "/_protected/payments/",
        "/_protected/subscription/",
        "/_protected/tools/"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/overlay": {
      "filePath": "overlay.tsx"
    },
    "/_protected/accounts/$id": {
      "filePath": "_protected/accounts/$id.tsx",
      "parent": "/_protected"
    },
    "/_protected/payments/$id": {
      "filePath": "_protected/payments/$id.tsx",
      "parent": "/_protected"
    },
    "/_protected/accounts/": {
      "filePath": "_protected/accounts/index.tsx",
      "parent": "/_protected"
    },
    "/_protected/active-game/": {
      "filePath": "_protected/active-game/index.tsx",
      "parent": "/_protected"
    },
    "/_protected/dashboard/": {
      "filePath": "_protected/dashboard/index.tsx",
      "parent": "/_protected"
    },
    "/_protected/notifications/": {
      "filePath": "_protected/notifications/index.tsx",
      "parent": "/_protected"
    },
    "/_protected/payments/": {
      "filePath": "_protected/payments/index.tsx",
      "parent": "/_protected"
    },
    "/_protected/subscription/": {
      "filePath": "_protected/subscription/index.tsx",
      "parent": "/_protected"
    },
    "/_protected/tools/": {
      "filePath": "_protected/tools/index.tsx",
      "parent": "/_protected"
    }
  }
}
ROUTE_MANIFEST_END */
