// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function HandleDiscordCallback(arg1) {
  return window['go']['main']['App']['HandleDiscordCallback'](arg1);
}

export function StartDiscordOAuth() {
  return window['go']['main']['App']['StartDiscordOAuth']();
}
