// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function HandleDiscordCallback(arg1:any):Promise<void>;

export function StartDiscordOAuth():Promise<Record<string, any>>;
